version: "3.7"
services:
  web:
    build: ./nginx
    ports:
      - "${HTTP_PORT}:80"

  app:
    build: ./app
    env_file:
      - .env
    volumes:
      - "./app/src:/app"
      - "./app/conf.d/php.ini:/usr/local/etc/php/php.ini"
      - profile:/tmp/xdebug

  profile-gui:
    image: jokkedk/webgrind
    volumes:
      - profile:/tmp
    ports:
      - "${PROFILE_PORT}:80"

volumes:
  profile:
