version: "3.7"
services:
  web:
    build: ./nginx
    ports:
      - "${HTTP_PORT}:80"

  app:
    build: ./app
    volumes:
      - "./app/src:/app"
      - "./app/conf.d/php.ini:/usr/local/etc/php/php.ini"